apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
  - port: {{ .Values.collectorService.port }}
    targetPort: {{ .Values.collectorService.port }}
  type: ClusterIP