apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector
data:
  collector.yaml: |
    receivers:
      zipkin:
        {{- include "aliyun-opentelemetry-collector.receiver" . | indent 8 }}
    exporters:
      alibabacloud_logservice/sls-trace:
        {{- include "aliyun-opentelemetry-collector.exporter" . | indent 8 }}
    service:
      pipelines:
        traces:
          receivers: [zipkin]
          exporters: [alibabacloud_logservice/sls-trace]