apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: otel-collector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: otel-collector
  minReplicas: {{ .Values.collectorHpa.min }}
  maxReplicas: {{ .Values.collectorHpa.max }}
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.collectorHpa.memoryUtilization }}